### ISSUE TITLE
Create UT framework for xcat-inventory

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-inventory#114]
More and more I am finding that changes to xcat-inventory breaks existing function, so I would like someone to spend time creating a UT framework that can be executed and the results pasted along with the pull request. 

Whenever we find a problem, we should strip down the underlying cause to what exposed the bug and create a .yaml file to `import` and a command to remove and add a UT case to the framework...

I think the testcase should be able to run on any existing xCAT install, and also clean up after itself so the namespace of the definitions do not conflict with existing xCAT definitions, something like `ut.xcat-inv.<name>`  so if we were creating an osimage definition, called "rhels7.5-compute" we would use `ut.xcat-inv.rhels7.5-compute` to make sure that we can detect the definitions created by the UT of xcat-inventory.

**Comment by immarvin** [comment]
will take a look on this. 
@robin2008  do you have some idea on python UT framework we can leverage?

**Comment by hu-weihua** [comment]
@whowutwut For base functions of `xcat-inventory`, we shipped more then 90 test cases in `xCAT-test`. we can easily use them by 

```
DSTMN=<mnip> xcattest -c xcat-inventory
```

The things need to be noticed:
* using xcat build after 20180906.0615, otherwise, you may hit issue https://github.com/xcat2/xcat-core/issues/5612

* there is one case named `import_osimage_with_environments_in_yaml` need more attributes, maybe need trigger it by below way

```
XCATTEST_CN=<cn>  XCATTEST_ISO=<iso> xcattest -t import_osimage_with_environments_in_yaml
```

So if you hope to run all test cases one time, run below command:

```
XCATTEST_CN=<cn>  XCATTEST_ISO=<iso> DSTMN=<mnip> xcattest -c xcat-inventory
```

**Comment by robin2008** [comment]
@immarvin   Normally we can use a unit test framework + `mock` module.
For unit test framework,  you can get lots from https://wiki.python.org/moin/PythonTestingToolsTaxonomy

I use the builtin `unittest` before,  but now I would suggest to try `pytest`

**Comment by zet809** [comment]
* [ ] Setup CI for xcat-inventory, leverage the current travs.pl
